### ISSUE TITLE
CRUD: Delete: 消除、刪除(remove, delete, erase, cancel, dismiss)該用哪個字？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#10]
原題目：「消除、刪除(remove, delete, erase, cancel, dismiss)該用哪個字？」

---
原題出處：

https://www.ptt.cc/bbs/Soft_Job/M.1594363672.A.7D0.html

> → yyc1217: remove delete erase cancel dismiss

**Comment by jason90929** [comment]
我的作法，供參：
delete：物件中移除某一 key, value(JavaScript 保留字的 delete object.key)
remove：陣列中移除某一筆資料
erase：未使用過，從字義上認為是清空某筆資料但記憶體位址保留
cancel：取消某個進入排程的服務，讓其回復至草稿階段或就緒階段；另一個接近的字為 stop，停止當前服務，差異大概是 cancel 會將進度 50% 返回至 0%，stop 則停留在 50%

**Comment by twy30** [comment]
@jason90929 



> 我的作法，供參：
> delete：物件中移除某一 key, value(JavaScript 保留字的 delete object.key)
> remove：陣列中移除某一筆資料
> erase：未使用過，從字義上認為是清空某筆資料但記憶體位址保留
> cancel：取消某個進入排程的服務，讓其回復至草稿階段或就緒階段；另一個接近的字為 stop，停止當前服務，差異大概是 cancel 會將進度 50% 返回至 0%，stop 則停留在 50%
> dismiss：開啟 modal 後將其關閉，同義字 close

# cancel vs. stop

這裡的對比很有意思 👍

讓我想到了更多相關字： abort, pause (以及對應的 undo/redo, re-try, resume, continue)

# dismiss vs. close

或許可以這樣說， dismiss 可以是「_有意識地_ (1) 檢查(examine)某資訊(warning, error)後 (2) 決定打發掉該資訊 ("close" 該 modal) 」。

**Comment by twy30** [comment]
Done.

* Google 簡報 https://bit.ly/2XazA2P
* Facebook 相簿 💬 https://bit.ly/2EsPmj9
* PTT 文章 💬 https://bit.ly/2DilNAm
* Twitter 討論 💬 https://bit.ly/2D57pM5

**Comment by twy30** [comment]
@jason90929

> cancel：取消某個進入排程的服務，讓其回復至草稿階段或就緒階段；另一個接近的字為 stop，停止當前服務，差異大概是 cancel 會將進度 50% 返回至 0%，stop 則停留在 50%

之前 "cancel, dismiss" 的討論，最後是往前端設計的方向發展 (*1) ；就後端來說，我開了新的討論串： https://github.com/EngTW/English-for-Programmers/issues/36 

---
*1:

> https://bit.ly/2XazA2P
>
> 讀者問題： Cancel vs. Dismiss （前端設計）
> 
> * Cancel 「取消」
>   * 適用於「讓使用者選擇停止、放棄正要進行的動作」
>   * 例如：「『發佈文章？』 Cancel （取消 👎 ） / OK （確認 👍 ）」
> * Dismiss 「廢棄某想法 / 屏除、遣散某人」
>   * 適用於「讓使用者打發掉提示、提醒、警告、錯誤訊息」
>   * 例如：「『＿＿首家線上賭場上線啦！』 Dismiss （朕知道了 🧐 ）」
