### ISSUE TITLE
複製(copy, clone, duplicate) 該用哪個字？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#17]

**Comment by jason90929** [comment]
我的用法，供參：
1. copy 我僅有用在從網頁中複製文字的按鈕的方法名稱「copyFromXXX」
2. clone 變數 ex: 
```
var clonedData = Object.assign({}, data);
```

3. duplicate 整個資料，且有操作到 API 且 DB 真的出了內容相同的新資料
```
var datumId = 1;
var duplicatedDatum = await duplicateDatum(datumId);
```

**Comment by twy30** [comment]
@jason90929 

> 我的用法，供參：
> 
> 1. copy 我僅有用在從網頁中複製文字的按鈕的方法名稱「copyFromXXX」
> 2. clone 變數 ex:
> 
> ```
> var clonedData = Object.assign({}, data);
> ```
> 
> 1. duplicate 整個資料，且有操作到 API 且 DB 真的出了內容相同的新資料
> 
> ```
> var datumId = 1;
> var duplicatedDatum = await duplicateDatum(datumId);
> ```

很有意思，我的理解如下：

* copy: 單一 value
* clone: 比「單一 value」範圍更廣的「物件」
* duplicate: 比「物件」範圍更廣、跨抽象層的資料

這樣與你描述的相符嗎？

**Comment by remorsecs** [comment]
我提供一些使用案例 (目前工作以 Python 為主)

1. copy
e.g. Python 語言內建的 copy 模組，其中有：shallow copy, deep copy
都是複製物件的值

2. clone
沒印象、可能太少遇到，不過我常用的一個框架 PyTorch 中有一個案例：
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.clone
用法和意思跟 Python 原生的 `.copy()` 幾乎一樣

3. duplicate
Diablo2 的 soj 之類的 (誤)
或是 IDE 的 複製一整行


我的經驗、感覺是 duplicate 似乎和另外兩個有明顯的不同，但是 copy 和 clone 好像沒有？
按照字典好像也是可以完全互通的字，好像差別在 copy 比較通俗一點？
https://www.ldoceonline.com/dictionary/copy
https://www.ldoceonline.com/dictionary/clone
https://www.ldoceonline.com/dictionary/duplicate
看起來 duplicate 似乎會有 "重複" 的意味？

討論一下

**Comment by twy30** [comment]
@remorsecs 

我的 *感覺* 是， clone 與 duplicate 似乎更強調「整體、過程複雜的複製」。

而 copy 相對地可以是只複製一部分。

例如說，

* 上下文脈絡在談「一份很多頁的文件」，我們只需要複製其中一句、一段、一頁時，我會說 "copy" 。
* 上下文脈絡在談「一台伺服器」，我們需要再組一台完全一樣配備的機器時，我會說 "clone" 或 "duplicate" 。

---
> duplicate
> Diablo2 的 soj 之類的 (誤)

😆😅

**Comment by twy30** [comment]
查了些語源學資料：

* copy
  * 14 世紀後期，「抄寫、複製 文字/文件」
  * 1640 年代，「模仿 (它人的例子)」
  * 1953 ，「複製電腦資料」
  * 1983 ，「送一份文件、信、 email 給第三方」
* clone
  * 1903 ，植物學，「出枝、出芽複製的植物」
  * 1970 ，「複製人、動物基因」
  * 1978 ，「 slavishly 模仿它人例子」
    * slavishly: > in a way that shows no attempt at originality
      * 或許可譯為「照本宣科」
      * > 照著本子念經文。比喻刻板的照著現成的文章或稿子宣讀，不知靈活運用。
* duplicate
  * 15 世紀早期，「雙份的」
  * 15 世紀晚期，「重覆(repeat)/複製一份」

---
* https://www.etymonline.com/word/copy
* https://www.etymonline.com/word/clone
  * https://www.moedict.tw/%E7%85%A7%E6%9C%AC%E5%AE%A3%E7%A7%91
* https://www.etymonline.com/word/duplicate

**Comment by lukelee0223** [comment]
英文詞性中，副詞通常用作"加強語氣"。
current, present都是在敘述目前時態，一個時間的過程，
像是：The development of technology until the present time (從....迄今)
now有強調語氣，當下，這個時間點，現在正在...
像是：Right now! Go Home! 或是 I say Now!
