### ISSUE TITLE
檢查(check, verify, validate)該用哪個字？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#18]

**Comment by adks3489** [comment]
照我經常遇到的慣例是
- check: 檢查運作狀態是否良好，例：檢查服務是否正常運作。
- verify: 確認內容是否正確，例：email verification
- validate: 驗證是否符合特定規格，例：表單的輸入是否符合格式。

**Comment by twy30** [comment]
@adks3489 感謝提供參考案例 😊 覺得蠻有道理的 👍
