### ISSUE TITLE
屬性: property vs. attribute 有什麼不一樣？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#25]

**Comment by adks3489** [comment]
[參考網頁](https://www.researchgate.net/post/What_are_the_differences_between_attribute_and_properties)
我從這篇問答感覺起來像是:
property: 描繪特性，一般會有固定的答案可選
attribute: 增加一些額外的資訊，內容不固定，如：name

不過這個兩個詞在HTML和DOM又有一點自己的定義。

同樣的也讓我想到argument和parameter的關係

**Comment by twy30** [comment]
@adks3489 

> 同樣的也讓我想到argument和parameter的關係

很有趣的聯想 👍 我開了 https://github.com/EngTW/English-for-Programmers/issues/31 來追蹤這個題目。

**Comment by twy30** [comment]
@adks3489 

我查了幾個線上英英字典，它們在解釋 attribute 時會用 property 這個字來描述，而在解釋 property 時也會用到 attribute 來描述 😅

> [參考網頁](https://www.researchgate.net/post/What_are_the_differences_between_attribute_and_properties)
> 我從這篇問答感覺起來像是:
> property: 描繪特性，一般會有固定的答案可選
> attribute: 增加一些額外的資訊，內容不固定，如：name

我查到的語源資料是：

* attribute: 來自拉丁文的 "assign" + "to"
* property: 來自拉丁文的 "one's own; particular"

配合你查的資料，還有我在 https://stackoverflow.com/a/21566583 看到的說法，或許可以這樣說：

* property 指的是一個東西它自身的性質，在 大部分/一般/常見 的情景、脈絡下都不會變的性質。
* attribute 指的是一個東西它「在相對狹隘的情景、脈絡下」所指派給它的特性

是故，我會這樣比喻，以「蘋果」來說，

* 蘋果是水果 ← property
* 這個裝在禮盒裡的蘋果是禮物 ← attribute

---
> 不過這個兩個詞在HTML和DOM又有一點自己的定義。

怎麼說？ 😊

**Comment by twy30** [comment]
@adks3489 

> 不過這個兩個詞在HTML和DOM又有一點自己的定義。

我還沒有細讀這個連結， https://stackoverflow.com/a/53924373 ；但想問一下，你說「這個兩個詞在HTML和DOM又有一點自己的定義」就是指 https://stackoverflow.com/a/53924373 裡說的意思嗎？

**Comment by twy30** [comment]
找到另一個討論 https://english.stackexchange.com/questions/28085/what-is-the-difference-between-attribute-and-property

我還沒時間去細讀 😅

**Comment by adks3489** [comment]
> @adks3489
> 
> > 不過這個兩個詞在HTML和DOM又有一點自己的定義。
> 
> 我還沒有細讀這個連結， https://stackoverflow.com/a/53924373 ；但想問一下，你說「這個兩個詞在HTML和DOM又有一點自己的定義」就是指 https://stackoverflow.com/a/53924373 裡說的意思嗎？

我指的是這個沒錯，我第一次感到類似的疑惑是在jquery遇到的attr跟prop

**Comment by twy30** [comment]
Reopening this issue -- this was incorrectly linked with pull request #37.

**Comment by twy30** [comment]
找到另一個資料： https://en.wikipedia.org/wiki/Property_(philosophy)#Intrinsic_and_extrinsic_properties

大意是：

* 「屬性、特質」可分為  intrinsic (固有的、內在的) 及 extrinsic (外在的)
* intrinsic property 是該物件固有的屬性，例如質量
* extrinsic property, 又稱 attribute, 是來自該物件與其它物件的「關係(relation)」，例如，重量 (受重力場影響)

**Comment by twy30** [comment]
# Attribute, Property 有什麼不一樣？

在哲學、語意上， attribute 偏向「由外部因素賦予此物件的屬性」， property 偏向「此物件內在本質的屬性」。

## Attribute

* 語意：外部(extrinsic) / 關係(relational) 屬性
  * 由「與其它物件的關係」賦予此物件的屬性
  * 例如，一個物件的「重量」；由此物件所處的重力場賦予的屬性
* 語源： 14 世紀後期，動詞「賦予、指派」，名詞「對某人的評價」
* 在程式上
  * 可表達物件、元素的屬性
  * 常用來表達「屬性的屬性」

## Property

* 語意：內部(intrinsic) 屬性
  * 物件本質上的屬性
  * 例如，一個物件的「質量」
* 語源： 1300 年代，本質、特性
* 在程式上
  * 可表達物件、元素的屬性

# Attribute, Property 該用哪個字？

在程式實作上，不同語言、框架、環境對於「物件屬性」這個觀念的心智模型多少有出入，並沒有一定的標準。

我個人偏好 C# 的風格。

## 以 C# 為例

* 在「為東西加註資料(metadata)」的情景下，用 `Attribute`
  * 例如， `DebuggerBrowsableAttribute`

* 而「類別的屬性」，稱為 `Property`
  * 例如， `String.Length`

## 以 HTML / DOM 為例

HTML (attribute) / DOM (property) 則是用了不同的字來表達「東西的屬性」。

引用 https://stackoverflow.com/a/53924373 的例子：

```
<input id="the-input" type="text" value="Name:">
```

* 假設使用者在此輸入欄位填上了 "foo"

* 接下來以 `<input>` 代表此 HTML 元素(element)

* 接下來以 `theInput` 代表此 DOM 物件

* 執行 theInput.value 會得到 "foo"
  * value 是 theInput 這個 DOM 物件的 property (屬性)

* 執行 theInput.getAttribute('value') 會得到 "Name:"
  * `getAttribute()` 是 theInput 這個 DOM 物件的方法
  * value 是 `<input>` 這個 HTML 元素的 attribute (屬性)

## 參考資料

* https://en.wikipedia.org/wiki/Attribute_(computing)
* https://en.wikipedia.org/wiki/Property_(philosophy)#Intrinsic_and_extrinsic_properties
* https://stackoverflow.com/a/53924373
* https://www.etymonline.com/word/attribute
* https://www.etymonline.com/word/property
* https://www.lexico.com/en/definition/attribute
* https://www.lexico.com/en/definition/property

感謝參與 https://github.com/EngTW/English-for-Programmers/issues/25 討論的網友。

**Comment by p4vega** [comment]
attribute和property的英文原意有所不同。
attribute是由人賦予的性質，例如木材是屬於環保材料，但或許不是所有的人都這麼認為。
property是原本就有的性質。例如木材是易燃的，不會因為任何想法而有所不同。
按照英文原義來思考的話，attribute應該翻譯成屬性，由人來分類歸屬而產生的性質；而property應該翻譯成特性，特性不會因人而異。
例：木材的特性之一是易燃，但也因此具有環保材料的屬性。
