### ISSUE TITLE
如何命名「回傳值(return value / result)」？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#3]
哪種方式比較好？

* ret (return 的簡寫)
* result
* 更有意義、更完整的變數名稱

**Comment by jiminhsieh** [comment]
個人覺得看情境

* 更有意義、更完整的變數名稱: 大多數的 application 應該是使用這個
* ret (return 的簡寫): 當你的使用會出現在 memory 受侷限的環境下，例如 RTOS 下
* result: 個人覺得不建議這個

**Comment by twy30** [comment]
@jiminhsieh 

> 個人覺得看情境

十分同意。

這也是我一直很想傳達給讀者的觀念：「要看情形」。

但我也能了解：從新手的角度來看，會希望答案愈簡單愈好。 😅

> * 更有意義、更完整的變數名稱: 大多數的 application 應該是使用這個

同意。

> * ret (return 的簡寫): 當你的使用會出現在 memory 受侷限的環境下，例如 RTOS 下

怎麼說？ 🤔

> * result: 個人覺得不建議這個

我想到，或許新手會受到框架的影響，例如 ASP.NET, 就有 `IActionResult` ( https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#iactionresult-type ).

**Comment by jiminhsieh** [comment]
>> * ret (return 的簡寫): 當你的使用會出現在 memory 受侷限的環境下，例如 RTOS 下

> 怎麼說？ 🤔

這邊想到的是 field name 會成為 payload 的一部分 (ex. JSON)，所以嚴格來說，跟這邊談的 local variable 無關 😅

**Comment by twy30** [comment]
@jiminhsieh 

> 這邊想到的是 field name 會成為 payload 的一部分 (ex. JSON)，所以嚴格來說，跟這邊談的 local variable 無關 😅

很有意思 🤔

我沒有接觸過這樣的需求，很好奇「手動省空間」 vs. 「用演算法壓縮 payload」在什麼樣的條件下，哪個會比較省什麼樣的資源 🤔

**Comment by jiminhsieh** [comment]
> 我沒有接觸過這樣的需求

我也沒直接接觸過(在上面開發)，但我的確遇過公司產品是 256 kB RAM 的，然後上面可能還要跑 RTOS (Linux 都還太肥的)，或是資源更侷限的，根本不是 OS 就是個 daemon 

> 很好奇「手動省空間」 vs. 「用演算法壓縮 payload」在什麼樣的條件下，哪個會比較省什麼樣的資源

其實我覺得一般來說『用演算法壓縮 payload』會比較好，但在 memory 很小之下，我推測通常 CPU 也會不夠強(我遇過 100 MHz 單核)，所以可能需要『手動省空間』

**Comment by twy30** [comment]
@jiminhsieh 

很有趣的案例 🤔 

> * 手動省空間: shift computation 到人腦，而且應該不像演算法壓縮可以全部性壓縮，但可以針對性地調整

或許，折衷方案是類似 網頁前端開發 minification 的做法，在 compilation 層動手，試著做到

* 給人讀的原始碼，保持可讀性
* 給機器讀的機械碼，節省資源

🤔

**Comment by twy30** [comment]
有人說它把「回傳值」命名為 `ofTheJedi`, 所以它的程式碼會像這樣：

```
return ofTheJedi;
```

😅

ref: https://softwareengineering.stackexchange.com/questions/134321/is-it-a-good-practice-to-name-the-returned-variable-result#comment251765_134321
