### ISSUE TITLE
建議用markdown直接寫在裡面

### ISSUE THREAD

**Issue by tbpfs** [EngTW/English-for-Programmers#33]
PTT的文看起來是
markdown  
但是PTT不支援阿!!
還不如直接放在github上

**Comment by twy30** [comment]
@tbpfs 

> 還不如直接放在github上

能理解 😅 我也在試著找到「讀者需求、製作成本」的平衡點。

* PTT Soft_Job 版的優點是它的社群文化與歷史，還有鄉民梗 😆
  * PTT 系統的弱點是如你提到的「不支援 markdown 」
    * 還有排版、字型、配色缺乏彈性
* Google 簡報的優點是「排版、字型、配色很方便」
  * 支援連結
  * 有講者稿(speaker notes)區可以裝文稿
  * 但格式上相對地封閉、不易搜尋
    * 比較偏向「作者 → 讀者」單向表達
* Facebook 相簿在互動上很方便
  * 缺點是無法更新「相片/圖」本身；只能更新「相片/圖的敘述文字」
* GitHub 這邊支援 markdown, 也有 issue 系統可以當討論區
  * 但在排版、字型、配色上缺乏彈性

---
我在想，或許 GitHub Pages 會是值得試試的選項 🤔

**Comment by StelaChiu** [comment]
希望可以直接放github，那四種連結都被公司鎖住了Orz

**Comment by twy30** [comment]
@StelaChiu 

> 希望可以直接放github，那四種連結都被公司鎖住了Orz

😲 你好，我想了解你所處的困境；請問一下，

* 你公司的網路是封了 `bit.ly` 短網址，還是 `ptt.cc` / `facebook.com` / `docs.google.com` 都被封住？
* 你公司的網路有封 `github.io` 或其它網域嗎？

**Comment by twy30** [comment]
補充說明：我這邊的問題是，一份東西我發佈在四個地方 (PTT, Google 簡報, Facebook 相簿, Facebook 文章) 。

東西發佈之後是不常需要改動，但若要改動/更正，就可能會要手動去調整 4 份資料 😅

是故，我這邊會需要找到「讀者需求、製作+維護成本」的平衡點；我想知道讀者的閱讀習慣/流程。

**Comment by adks3489** [comment]
我覺得比較常見的應該還是GitHub Pages，
對於讀者的查閱也會比較容易。

另外在未來有協作需求的話，也比較容易配合github提供的功能來達成。

類似的repo有：
- https://github.com/isocpp/CppCoreGuidelines
- https://github.com/google/styleguide

**Comment by StelaChiu** [comment]
> @StelaChiu
> 
> > 希望可以直接放github，那四種連結都被公司鎖住了Orz
> 
> 😲
> 
> 你好，我想了解你所處的困境；請問一下，
> 
> * 你公司的網路是封了 `bit.ly` 短網址，還是 `ptt.cc` / `facebook.com` / `docs.google.com` 都被封住？
> * 你公司的網路有封 `github.io` 或其它網域嗎？

@twy30 
哈囉，我們公司是封掉ptt, fb, twitter跟其他類似網站
docs.google有時可以有時候又不行，雲端硬碟類的也是全鎖
github.io倒是沒問題

我是從ptt看到文章的，主要是想分享給同事看
另外個人是覺得搜尋功能比較重要，畢竟要用到時還是需要再回來查一下 😆

**Comment by twy30** [comment]
感謝各位的意見回饋。

綜合以上的討論，我把需求拆開來：

* (1) 可讀性 ← 對 markdown 的支援
* (2) 製作工法 ← 對 排版、配色、外部連結 的支援
* (3) 可讀性 ← 對 搜尋、查詢功能 的支援
* (4) 營運、維護成本 ← 一稿多平台發佈、更新
* (5) 可讀性 ← 繞過 網域黑名單 的限制

---
考慮到人力有限 😅 ，我打算這麼做：

以目前的「週刊」模式來說，

* 以後新的週刊文稿會放一份在 GitHub 這裡
* 目前既有的文稿也會放一份上來

能看到 https://github.com/EngTW/English-for-Programmers/ 的話，就能直接看到文稿。

這應該能改善以下幾點

* (1) 可讀性 ← 對 markdown 的支援
* (5) 可讀性 ← 繞過 網域黑名單 的限制

---
長期來說，會 **想** 往 GitHub Pages 的方向走。

* 「週刊」可能會從目前的「可以直接閱讀的內容」變成「內容更新摘要」的「週報」
* 既有週刊內容可能會拆開重整為更好檢索的獨立項目
* 技術上來說，會希望能在「 markdown 的清爽 與 HTML 的豐富 (排版、配色、外部連結、表格、圖) 」之間找到平衡

以改善以下幾點：

* (2) 製作工法 ← 對 排版、配色、外部連結 的支援
* (3) 可讀性 ← 對 搜尋、查詢功能 的支援
* (4) 營運、維護成本 ← 一稿多平台發佈、更新

---
再次感謝各位 😊

**Comment by twy30** [comment]
@tbpfs @StelaChiu 

* 我把 PTT 文稿複製了一份到 https://github.com/EngTW/English-for-Programmers/tree/master/notes
* 更新了 https://github.com/EngTW/English-for-Programmers/blob/master/ReadMe.md
  * 在每週文章下的「PTT 文章」列出「連往 notes 」的連結

---
@adks3489 

長遠來說，會想往 GitHub Pages 的方向走。

目前打算再多累積幾週的內容，更了解對於「檢索、排版」的需求後，再來看看要怎麼實作。

---
再次感謝各位的意見回饋。 😊
