### ISSUE TITLE
分開: detach vs. separate vs. split 有什麼不一樣？ 

### ISSUE THREAD

**Issue by LPenny-github** [EngTW/English-for-Programmers#35]
PowerShell 動詞表推薦 split
但我想知道更多，謝謝大大 orz

**Comment by twy30** [comment]
我的 *感覺* 是：

* detach: 從個體之間明確的連接點分開，可以是實體上的「把相機從三腳架分開」，也可以是抽象的「情感上的抽離」。
* separate: 不像 detach 那樣「從個體之間明確的連接點分開」，例如，「把牛奶分離成乳酪與乳清」。
* split: 強調一個個體分離成多塊，例如，「一條路分岔成兩條路」。

就程式寫作來說，我印象中有這樣的例子

* detach 用在「卸載資料庫」
* split 用在「分割字串」

對 separate 比較沒印象 🤔

**Comment by adks3489** [comment]
結合上面跟我的經驗是：

- detach: 把原本兩個就能獨立的個體拆開，拆開後兩個都還能運行
  - 例如：thread detach, process detach、附件的attach相反也是detach
- separate: 把原本緊密結合的東西拆開，像是化學分離
  - 寫code的時候我也沒印象，不過關注點分離 (Separation of concerns)也是用這個字眼
- split: 比較像是物理切割，將一個個體分開後，每個個體的本質還是一樣的東西
  - UI的Layout切割也會用split

**Comment by LPenny-github** [comment]
謝謝兩位大大 orz
