### ISSUE TITLE
如何表達資料從哪邊來，又要給誰

### ISSUE THREAD

**Issue by SyuanTsai** [EngTW/English-for-Programmers#38]
如果想表達資料從哪邊取得該怎樣命名英文表較合適呢？

舉例：API回應
我會寫ApiResponse{From/IN/By/For}資料， 
但也有人會寫Get資料，
但在程式維護上會不知道這資料從哪邊來的，變成要去追蹤程式。

如果要給別人
To、Send、Set

**Comment by twy30** [comment]
@carsun00 你好，很抱歉剛剛才注意到這個題目；不知道為什麼我的 [GitHub notifications](https://github.com/notifications) 沒有列出這個 issue 🤔

---
> 如果想表達資料從哪邊取得該怎樣命名英文表較合適呢？

我覺得你列出來的 from, in, by, for, to 都是可以的，可以組成這樣的形式：

* 變數： `名詞` + `敘述短句` ；例如
  * `data` + `From` + `Server1` = `dataFromServer1`
* 方法： `動詞` + `資料` + `敘述短句` ；例如
  * `GetEmployeeById`
  * `WriteLogToDisk`

---
如果你有不確定的情形，可以貼上來一起研究看看 😊
