### ISSUE TITLE
validate vs verify

### ISSUE THREAD

**Issue by jiminhsieh** [EngTW/English-for-Programmers#45]
不知道能不能用 validation vs verification 來學差異？

可以的話

> According to the IEEE Standard Glossary of Software Engineering Terminology, verification is defines as "The process of evaluating a system or component to determine whether the products of a given development phase satisfy the conditions imposed at the start of that phase." Validation, on the other hand, is defined as "The process of evaluating a system or component during or at the end of the development process to determine whether it satisfies specified requirements."

https://users.ece.cmu.edu/~koopman/des_s99/verification/

**Comment by twy30** [comment]
@jiminhsieh 

Wikipedia 上也有類似的說法：

* https://en.wikipedia.org/wiki/Verification_and_validation

其中這個講得最直白：

* https://en.wikipedia.org/wiki/Software_verification_and_validation

> * Verification: Are we building the product right?
> * Validation: Are we building the right product?

---
就溝通上來說，不管是使用哪個字，對方多半都能聽懂你想表示的意思是「檢驗某事物Ｘ是真是假、正不正確、邏輯上合不合理」的動作。

如果要講究語意的話，

* verify 偏向「已經知道什麼是正確的狀態，然後來比對要檢驗的東西是否合乎『你預期的正確的狀態』」。

參考上面的 "Are we building the product right?" ；你已經先有產品設計圖/規格書，然後來比對做出來的產品是否與設計圖一致、是否符合規格書的要求。

寫成程式就會像是 `VerifyUserPassword()`; 你已經知道正確的使用者密碼(的 hash)，你現在要來比對你拿到的資料是否與你預期的「正確的密碼(的 hash)」一致。

* validate 偏向「檢驗某個東西是否合乎規範、標準、原則；是否邏輯連貫、合理」。

參考上面的 "Are we building the right product?" ；你會去思考你是否有真正了解使用者的需求，有正確地為問題定框(frame)，設計出來的 solution 是解決了真正的問題。

寫成程式就會像是 `ValidateUserPassword()`; 會去檢驗 entropy 夠不夠，是不是已知不安全的密碼，等等。

---
另一種做法，就是通通用 check 代替 😆

例如， `CheckUserPassword()` + 註解；別人多半能看得懂你是想寫個方法來「檢查使用者密碼」，然後再去看文件進一步了解你的意圖。 😅

**Comment by twy30** [comment]
# 「驗證」 validate vs. verification

剛想到一個題目：「年齡 驗證」， "age validation" vs. "age verification"

---
Google 拜出來的結果是：

* age validation: 75 千 個結果
* age verification: 14800 千 個結果

---
netspeak.org 拜出來的結果是：

* age validation: 3.4 千 個結果
* age verification: 110 千 個結果

---
# 分析 Google 前五頁的結果: "age validation"

第 1 頁前幾個搜尋結果是在談

* 「輸入的生日字串的格式是否滿足 dd/MM/yyyy 」
* 「排除小於 0 或大於 100 的輸入值」
* 「計算是否滿 18 歲」

接下來 4 頁多是在談「鑑定生物年齡的科學研究方法，要怎麼做才準確」 (尤其是鑑定水產品、魚的年齡) 🤔

---
# 分析 Google 前五頁的結果: "age verification"

"age verification" 大多是指「驗證年齡是否滿足對於上限/下限的要求 → 以使用者的年齡來判斷它做這件事合不合法」。

---
# 我的解讀

與 https://en.wikipedia.org/wiki/Software_verification_and_validation 提到的觀念類似：

> * Verification: Are we building the product right?

「(與設計圖、規格書相比，) 我們有沒有把產品做對？」

> * Validation: Are we building the right product?

「我們在做的是不是對的產品？ (有沒有真正從本質上解決客戶的問題、滿足它們的需求？)」

---
"age validation" vs. "age verification" 的差異在於

* "age validation": 「我們對 某生物的年齡的判斷 對不對？」

* "age verification"：　「這人的年齡是否合乎『已達法定年齡』的狀態？」

**Comment by twy30** [comment]
又想到一個題目： "device validation" vs. "device verification" ；但還沒時間去仔細研究 😅

**Comment by linmasaki** [comment]
我這邊對於 "Verify" vs "Validate" 是結合之前上 PMP 課程時, 講師有特別提到做 Verify 的步驟通常會在 Validate 之前
- Verify: 檢查產品或產品製造流程有沒有符合規格書的要求 
- Validate: 產品能不能被客戶驗收 

所以這邊我自己的看法是 Verify(Verification) 會用在你輸入的資料必須要合乎我規定的格式, 而 Validate(Validation) 則是你輸入的資料我確認過了也接受了(有沒有合乎規則就是不是那麼重要). 

這邊附上網路上找到的參考[連結](https://www.brainbok.com/guide/pmp/study-notes/verification-vs-validation/)

**Comment by twy30** [comment]
我剛再讀了一次 https://en.wikipedia.org/wiki/Software_verification_and_validation ，看到它列出 4 種組合 🤔

`{software, artifact/specification}` * `{verification, validation}`

我要再來看看這 4 個脈絡下， verification/validation 是怎麼定義的 🤔

**Comment by twy30** [comment]
> 我剛再讀了一次 https://en.wikipedia.org/wiki/Software_verification_and_validation ，看到它列出 4 種組合 🤔
> 
> `{software, artifact/specification}` * `{verification, validation}`
> 
> 我要再來看看這 4 個脈絡下， verification/validation 是怎麼定義的 🤔

# IEEE 1012: Verification and Validation

## Verification

「開發過程可分成多個階段；每個階段收尾時，驗證『成品是否滿足此階段的目標？』」

例如說：

* 需求Ｒ：「做出整數加法器」

* 設計階段：輸入Ｒ，輸出規格書Ｓ
  * 規格書Ｓ會定義整數輸入格式、加法的演算法、如何處理溢位、等等
  * 就「設計階段」而言， verification 會驗證「規格書Ｓ是否能滿足需求Ｒ？」

* 實作階段：輸入Ｓ，輸出程式Ｐ
  * 就「實作階段」而言， verification 會驗證「程式Ｐ是否能滿足規格書Ｓ？」

也就是驗證「有沒有把東西做對？」，而「對」的定義由該開發階段的「輸入」來判斷。

## Validation

「開發過程可分成多個階段；每個階段收尾時，驗證『成品是否滿足此階段的目的？』」

例如說：

* 需求Ｒ：「做出整數加法器」
  * validation 驗證內容包括「整體來看，整數加法器真的是最適當的解決方案嗎？」

* 設計階段：輸入Ｒ，輸出規格書Ｓ
  * validation 驗證內容包括「規格書Ｓ開出來的執行條件、技術限制合理嗎？」

* 實作階段：輸入Ｓ，輸出程式Ｐ
  * validation 驗證內容包括「程式Ｐ的使用體驗如何？是否真正解決了使用者的問題？」

也就是驗證「有沒有做對的東西？」，而「對」的定義由更高層次的整體「目的」來判斷。

---
參考資料：

* https://en.wikipedia.org/wiki/Verification_and_validation
* https://en.wikipedia.org/wiki/Software_verification_and_validation

**Comment by twy30** [comment]
已整理至 https://github.com/EngTW/English-for-Programmers/blob/master/notes/2020-08-21-validate-verify.md

**Comment by twy30** [comment]
如果覺得還有問題、疑慮，歡迎再開新 issue 來討論 😊
