### ISSUE TITLE
如何命名「總和(Sum)、總數(Total)變數」？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#5]
什麼時候該用哪個字？該怎麼用？

* Sum
* Total

**Comment by Typas** [comment]
我個人是認為語意上來說，Total指全部，而Sum的意義偏向加總。
如果以人口舉例：
TotalPopulation表示全世界的人口總數，
SumOfAsia則是指亞洲地區的人口數總和。

如果要強調總體的概念，會偏向使用Total；
要強調加總的對象，則會偏向使用Sum。

**Comment by twy30** [comment]
@Typas

> 如果要強調總體的概念，會偏向使用Total；
> 要強調加總的對象，則會偏向使用Sum。

十分同意 👍

---
從語法的層面想，

* Sum 可以做為 名詞、動詞
* Total 可以做為 名詞、形容詞
  * 在英文裡， total 是可以當 動詞 的，但在程式碼裡，我很少看到如此用。

**Comment by twy30** [comment]
This is resolved by pull request #37.
