### ISSUE TITLE
第Ｎ個要怎麼命名

### ISSUE THREAD

**Issue by halfdonees** [EngTW/English-for-Programmers#53]
你好，我最近在處理股票資料的api，
有一個內容是我想要將資料整理成K線的形式，
我的Kbar calss中想要存「屬於今天中的第N根Kbar」，這種狀況要怎麼命名呢。

像是以一根10:00~ 10:15的15分鐘k線，8:45開盤，這個變數會存5，代表是今天的第六根K線

**Comment by adks3489** [comment]
我還蠻常遇到類似情況的。
我一般會用bar index當作iterator的命名，
如果是要存在每根K Bar上的屬性，我會用index of day或是index of session(有要分盤的話)

**Comment by twy30** [comment]
@halfdonees 你好 😊

可以考慮 `ordinal` 這個字，它可作為 "ordinal number" (序數) 的簡寫。

## 實際應用案例

.NET 的 `DataColumn` 就是用 `int Ordinal` 來表示該 `DataColumn` 是「資料表格(`DataTable`) 的 *第幾縱行*」

```csharp
public int Ordinal { get; }
```

## 參考資料

* 序數： https://zh.wikipedia.org/zh-tw/%E5%BA%8F%E6%95%B0
* https://www.lexico.com/definition/ordinal
* https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn.ordinal?view=netcore-3.1

**Comment by twy30** [comment]
@adks3489 

> index

同意， `index` 也不錯 👍 ；在程式設計這個領域，我相信大多數人都可以從 index 聯想到 array index 的觀念。

`ordinal` (序數) 更帶有「順序」的語意 (以及其數學上的性質，可參考 https://en.wikipedia.org/wiki/Ordinal_number ) 🤔

---
其它 *相對地沒那麼貼切但或許可以考慮看看* 的選項 😅

* key
* id
* name
