### ISSUE TITLE
如何命名「集合名詞(collective noun)數量變數」？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#6]
例如說，

population (人口) 算是哪種？

* 💧 不可數名詞
* 🐈 可數生物
* 📦 可數非生物

似乎 count / number / quantity 都可以用在 population 上？

---
其它像是

* army
* team

似乎會用 size 這個字？

---
或許集合名詞 👨‍👩‍👧‍👦 有它自己的規則？

* ammo / ammunition

---
Related: #2

**Comment by jason90929** [comment]
除了 data, datum; children, child 有特別字
我會乾脆直接加s（audiences）；有時則會使用 pluralOfAudience, singularOfAudience

**Comment by twy30** [comment]
@jason90929 

> 有時則會使用 pluralOfAudience, singularOfAudience

很有意思 🤔 能不能描述一下 pluralOfAudience / singularOfAudience 的使用案例、情景、上下文？
