### ISSUE TITLE
《程式英文》近況 2020-10-17 🤔

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#68]
連續兩週沒更新了 orz

過去兩週生活雜務過載，尤其是一些自宅維修工程。

希望下週能回來繼續耕耘《程式英文》 😊

**Comment by gy0857478** [comment]
期待!

**Comment by twy30** [comment]
最新更新：「刷 LeetCode 練習命名」 https://github.com/EngTW/English-for-Programmers/pull/90
