### ISSUE TITLE
縮寫、簡寫的優缺點 ？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#7]
https://www.ptt.cc/bbs/Soft_Job/M.1594363672.A.7D0.html

> → testPtt: 基本上不用Quantity 太長

> → bheegrl: ammoQty

> 推 dks50217: Cnt

> 推 enthos: pn, an, bg, hp \ Forth(Write-only lang.) style.

> 推 dces4212: nr_student

> 推 Bencrie: nr_ 這個是 Linux kernel 的命名

> 完全能理解，縮寫、簡寫、更短的字、更簡潔的寫法，只要能解決問題，都是好的。

**Comment by twy30** [comment]
> 推 Bencrie: nr_ 這個是 Linux kernel 的命名

https://stackoverflow.com/questions/8306202/what-does-nr-stand-for-in-system-call-number-that-is-usually-used-as-suffix

---
https://en.wikipedia.org/wiki/Numero_sign#Nr.

> In some languages, Nr., nr., nr or NR is used instead, reflecting the abbreviation of the language's word for 'number'.

**Comment by magussiro** [comment]
推Qty,Cnt 簡寫，應該不太會想到別的字

**Comment by twy30** [comment]
剛用 "common abbreviations in source code" 去拜 Google, 發現有人整理了列表

https://github.com/kisvegabor/abbreviations-in-code

裡面的確有些縮寫是蠻直覺的；又，或著說，看多了就看習慣了 😅

**Comment by twy30** [comment]
之前看到另一個案例： `PV = NRT` 這樣的科學計算。

或許一個折衷方案是：

* 如果是在「講相近的專業語言」的領域裡，用那個領域語言的常用簡稱，當然是沒問題的
* 如果要跨領域合作，那自然就得選定「[通用語](https://zh.wikipedia.org/zh-tw/%E9%80%9A%E7%94%A8%E8%AA%9E)([lingua franca](https://en.wikipedia.org/wiki/Lingua_franca)」

就要註解一下： 

```
var p // pressure
var v // volume
...

PV = NRT
```

**Comment by twy30** [comment]
或許這個題目最後會收斂在這樣子的結論 😅

> A language is a dialect with an army and navy.
> 語言就是有武力的方言。

ref: https://en.wikipedia.org/wiki/A_language_is_a_dialect_with_an_army_and_navy

---
也就是說，在這個「縮寫、簡寫的優缺點」題目的脈絡下，誰的生產力高、誰產出的價值多，它的偏好就會成為那個環境中的標準。 😅

會是每個人去評估「我付出這樣的認知成本以換回來的利益，是賺是賠？」，而不會是從技術層面的辯論來決定「『縮寫、簡寫與否』是好是壞」 🤔

**Comment by twy30** [comment]
參考討論： https://github.com/EngTW/English-for-Programmers/issues/4
