### ISSUE TITLE
台式英文、漢語拼音、日文拼音的優缺點？

### ISSUE THREAD

**Issue by twy30** [EngTW/English-for-Programmers#8]
https://www.ptt.cc/bbs/Soft_Job/M.1594363672.A.7D0.html

> 推 vi000246: 我喜歡台式英文 bulletWeight remainLife

> 推 goldflower: 看過中國人用拼音寫扣 jin_jia_ki_si

> 推 gasbomb: 上一份工作看到的 氣死https://i.imgur.com/x9GmljV.jpg 

> → OrzOGC: 用拼音真的...還有日文拼音的...冏...

> 完全能理解，解決問題優先。

> 語言能做到優雅當然是好，但最重要的功能還是溝通（人與人的溝通、人與機器的溝通）。

**Comment by adks3489** [comment]
我覺得除非能保證程式碼「永遠」只有「本地人」在看以外（還要一眼能看懂），拼音都不是好的選擇。

**Comment by twy30** [comment]
@adks3489 

> 我覺得除非能保證程式碼「永遠」只有「本地人」在看以外（還要一眼能看懂），拼音都不是好的選擇。

完全能理解這個考量 👍

---
換個角度，有時候我會好奇，如果是以下兩者相比

1. 意義完整的拼音變數名稱
2. i, j, k, var1, var2, var3, arg1, arg2

不知道哪個讀起來比較痛苦？ 🤔😅

**Comment by magussiro** [comment]
> @adks3489
> 
> > 我覺得除非能保證程式碼「永遠」只有「本地人」在看以外（還要一眼能看懂），拼音都不是好的選擇。
> 
> 完全能理解這個考量 👍
> 
> 換個角度，有時候我會好奇，如果是以下兩者相比
> 
> 1. 意義完整的拼音變數名稱
> 2. i, j, k, var1, var2, var3, arg1, arg2
> 
> 不知道哪個讀起來比較痛苦？ 🤔😅

個人認為method裡面的temp variables不一定要管，但method一定要語意清晰

**Comment by twy30** [comment]
@magussiro 

> 個人認為method裡面的temp variables不一定要管，但method一定要語意清晰

很有道理 👍

若 method/function 的名稱能清楚表達它的「動作/行為」，對於理解程式碼 上 (類別) 下 (變數) 文脈絡會很有幫助。

可以把注意力放在 全域變數(global variable) 上。

**Comment by twy30** [comment]
如果把題目延伸到「用英文以外的語法/字母來寫程式」，昨天看到一個很有趣的例子 😆

`outputStream.🚽`

**Comment by twy30** [comment]
除了漢語拼音、日文羅馬拼音外，看到了其它類似的辯論，例如

* 美式英文 vs. 英式英文
* 只用 ASCII
  * 加入希臘字母 (例如 `Δt` )
  * 加入 sub/super script (例如 `aₙ₊₁` = `aₙ` + 1 )
  * "accent" 字母，例如 fiancé vs. fianc
* 其它語言： 德文、西班牙文

我正在整理這些案例與辯論內容。

**Comment by twy30** [comment]
最後整理成「美式英文 + ASCII」 vs. 其它寫作組合的「成本 vs. 效益」。

大致上來說，

1. 先把程式寫對；「滿足需求、解決問題」以創造價值
2. 往「美式英文 + ASCII」靠攏有「技術相容」的好處
3. 「正確、清楚、簡潔的母語資訊」好過「模糊的英文資訊」

---
* Google 簡報： https://bit.ly/32rtGy3
* Google 簡報原始檔： https://bit.ly/2DGDhXd
* Facebook 相簿 💬 ： https://bit.ly/3fCF2mv
* PTT 文章 💬 ： https://bit.ly/3eD2VsO
* GitHub 討論串 💬 ： https://bit.ly/2ZGifkl
* Twitter 討論串 💬 ： https://bit.ly/2ZGtY2l
