### ISSUE TITLE
如何命名「幾小時內更新」變數

### ISSUE THREAD

**Issue by weimily-zz** [EngTW/English-for-Programmers#95]
程式需要 query 「在多久時間內發生動作」的資料，像是幾天內建立、幾小時內更新，  
想把這樣的設定抽出來放在 config 統一管理，應該怎麼命名才好呢？  
如果要加上受詞，比如「幾小時內更新的文章」，又應該怎麼命名？  
比起省略，是否更建議加上受詞？

**Comment by twy30** [comment]
@weimily 你好 😊

以「幾小時內更新的文章」為例，假設無上下文脈絡的輔助，我目前想到兩種可能性：

---

```XML
<!-- 「在過去Ｘ小時內更新的文章」 -->
<PostsUpdatedWithinPastXHours>24</PostsUpdatedWithinPastXHours>
```

從語法上來看，「在過去Ｘ小時內更新的文章」的名詞是「文章」，但對學過代數的讀者來說，應該能從「Ｘ」與 `24` *會意* 到 「在過去Ｘ小時內更新的文章」的主角是那「Ｘ」。

---

```XML
<!-- 「文章更新歷史查詢時間長度（以小時計）」 -->
<PostUpdateHistoryQueryTimeSpanInHours>24</PostUpdateHistoryQueryTimeSpanInHours>
```

**Comment by twy30** [comment]
@weimily 

> 幾天內建立、幾小時內更新

延伸 https://github.com/EngTW/English-for-Programmers/issues/95#issuecomment-740921846 的 `Within-Past-X-Units` 格式，可以有以下的可能性

* `ItemCreatedWithinPastXDays`
* `ItemModifiedWithinPastXHours`

---

或者，

* `ItemCreationHistoryQueryTimeSpanInHours`
* `ItemModificationHistoryQueryTimeSpanInDays`

---

以 C# 來說，有 `TimeSpan` 這個類別 ( https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=net-5.0 ), 也可以選擇省去上述例子中最後的「單位」 ( `InUnits` ); 也就是預期熟悉 C# 的讀者 *已知* `TimeSpan.Parse()` 能接受的文字格式。

---

以上可以參考看看 😊

**Comment by weimily-zz** [comment]
我想問的是第一種情境，沒有清楚表達不好意思 😅
謝謝你的建議，那這個 issue 我就先關掉囉~
